import { Octokit } from "@octokit/rest";
import dotenv from "dotenv";
import * as yaml from "js-yaml";

dotenv.config();

export interface AutoPROptions {
  owner?: string;
  repo?: string;
  baseBranch?: string;
}

export async function createAutoPR(
  proposedFailIf: string,
  correctionPrompt: string,
  proposerId: string,
  options?: AutoPROptions
): Promise<string> {
  const token = process.env.GITHUB_TOKEN;
  const owner = options?.owner || process.env.GITHUB_OWNER || "simdorei";
  const repo = options?.repo || process.env.GITHUB_REPO || "legal_harness";
  const baseBranch = options?.baseBranch || process.env.GITHUB_BASE_BRANCH || "main";

  if (!token) {
    console.warn("⚠️  [GitOps] GITHUB_TOKEN is not set. Falling back to mock PR URL for testing.");
    return `https://github.com/${owner}/${repo}/pull/mock-${Date.now()}`;
  }

  const octokit = new Octokit({ auth: token });
  const timestamp = Date.now();
  const branchName = `auto-evolve-${timestamp}`;
  const ruleId = `QG-AUTO-${timestamp}`;

  console.error(`🚀 [GitOps] Creating branch '${branchName}' from '${baseBranch}' on ${owner}/${repo}...`);

  // 1. Get SHA of the base branch
  const { data: baseRef } = await octokit.rest.repos.getBranch({
    owner,
    repo,
    branch: baseBranch,
  });
  const baseSha = baseRef.commit.sha;

  // 2. Create new branch ref
  await octokit.rest.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha: baseSha,
  });

  // 3. Get existing fail-cases.yaml
  let fileSha: string | undefined;
  let currentContent = "";
  try {
    const { data: fileData } = await octokit.rest.repos.getContent({
      owner,
      repo,
      path: "fail-cases.yaml",
      ref: branchName,
    });

    if ("content" in fileData && !Array.isArray(fileData)) {
      fileSha = fileData.sha;
      currentContent = Buffer.from(fileData.content, "base64").toString("utf-8");
    }
  } catch (err: any) {
    if (err.status !== 404) throw err;
  }

  // 4. Append new rule to YAML structure
  let parsedYaml: any = { gates: [] };
  if (currentContent.trim()) {
    try {
      const loaded: any = yaml.load(currentContent);
      if (loaded && Array.isArray(loaded.gates)) {
        parsedYaml = loaded;
      }
    } catch (e) {
      console.error("Failed to parse existing YAML, initializing fresh structure.");
    }
  }

  const newGate = {
    id: ruleId,
    name: `Crowdsourced Rule by ${proposerId}`,
    source_case: `EVOLVE-${timestamp}`,
    trigger_condition: `주제 == '자동제안' AND '${proposerId}'`,
    fail_if: proposedFailIf,
    correction_prompt: correctionPrompt,
  };

  parsedYaml.gates.push(newGate);
  const updatedYamlContent = yaml.dump(parsedYaml, { indent: 2, lineWidth: -1 });

  // 5. Commit updated fail-cases.yaml to new branch
  await octokit.rest.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: "fail-cases.yaml",
    message: `feat(harness): auto-propose rule ${ruleId} by ${proposerId}`,
    content: Buffer.from(updatedYamlContent).toString("base64"),
    sha: fileSha,
    branch: branchName,
  });

  // 6. Create Pull Request
  const prTitle = `[Auto-Evolve] Rule Proposal ${ruleId} (${proposerId})`;
  const prBody = `### 🤖 Autonomous Quality Gate Proposal
- **Proposer:** \`${proposerId}\`
- **Rule ID:** \`${ruleId}\`
- **Violated Pattern (fail_if):**
  > ${proposedFailIf}
- **Correction Directive:**
  > ${correctionPrompt}

---
*Generated by K-Tax Agent Supreme Judge Pipeline. Please review and merge to activate this rule.*`;

  const { data: pr } = await octokit.rest.pulls.create({
    owner,
    repo,
    title: prTitle,
    head: branchName,
    base: baseBranch,
    body: prBody,
  });

  console.error(`✅ [GitOps] Successfully opened PR: ${pr.html_url}`);
  return pr.html_url;
}
