import { createHash } from 'node:crypto';
import { agentPrompt, antigravityConfig, cursorConfig, geminiConfig, gptInstructions, mcpEndpoint, vscodeConfig } from './setup.js';

const escapeHtml = (text: string) => text.replace(/[&<>"']/g, value => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
}[value]!));
const codeBlock = (id: string, label: string, text: string) => `<div class="code-head"><span>${label}</span><button class="copy" data-copy="${id}">${label} 복사</button></div><pre><code id="${id}">${escapeHtml(text)}</code></pre>`;
const style = `
:root{color-scheme:light;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI","Malgun Gothic",sans-serif;color:#183044;background:#f5f7fb;font-synthesis:none}
*{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:24px}body{margin:0;line-height:1.75;word-break:keep-all}a{color:#205bb7;text-underline-offset:4px}button,a,summary{touch-action:manipulation}button{font:inherit;cursor:pointer}a:focus-visible,button:focus-visible,summary:focus-visible{outline:3px solid #dfab3f;outline-offset:5px}.wrap{max-width:1060px;margin:auto;padding:0 28px}.skip{position:absolute;left:16px;top:-80px;padding:10px 18px;background:white;z-index:2}.skip:focus{top:12px}
header{border-bottom:1px solid #dce3ee;background:#fff}nav{min-height:78px;display:flex;align-items:center;justify-content:space-between;gap:24px}.brand{color:#142e45;text-decoration:none;font-size:23px;letter-spacing:-1px;font-weight:800}.brand span{font-size:14px;font-weight:500;letter-spacing:0;margin-left:12px;color:#506579;border-left:1px solid #cbd5e1;padding-left:14px}.nav-links{display:flex;gap:22px;font-size:14px}.nav-links a{color:#344c60;text-decoration:none}.nav-links a:hover{text-decoration:underline}
.intro{padding:62px 0 32px;max-width:760px}.eyebrow{color:#245bb0;font-size:13px;font-weight:750;letter-spacing:.1em;margin:0 0 16px}h1{font-size:clamp(32px,4.3vw,48px);line-height:1.3;letter-spacing:-.055em;margin:0 0 20px;font-weight:800}.lede{font-size:17px;color:#465d70;margin:0;max-width:620px}.key-note{font-size:14px;color:#53677b;margin:18px 0 0}.key-note strong{color:#183b68}
.apps{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;margin:0 0 28px}.app-card{background:#fff;border:1px solid #d7e1ed;border-radius:14px;padding:25px;display:flex;flex-direction:column;align-items:flex-start}.app-card.featured{border-top:4px solid #27599b;padding-top:22px}.app-card h2{font-size:23px;line-height:1.3;margin:10px 0 12px;letter-spacing:-.04em}.badge{color:#526c89;font-size:12px;font-weight:650;letter-spacing:.015em}.app-card p{font-size:14px;color:#506579;margin:0 0 20px;flex:1}.app-card .sub-link{margin-top:10px;font-size:13px}.button{display:inline-flex;align-items:center;justify-content:center;border:1px solid #c2d1e5;border-radius:8px;padding:10px 17px;background:#fff;color:#244e84;text-decoration:none;font-size:14px;font-weight:700;min-height:44px}.button:hover{background:#eef4ff}.button.primary{background:#204f88;color:white;border-color:#204f88}.button.primary:hover{background:#153c6d}
.compatibility{width:100%;border-collapse:collapse;margin:0 0 24px;font-size:14px;background:#fff}.compatibility caption{text-align:left;font-weight:700;padding:0 0 10px}.compatibility th,.compatibility td{text-align:left;vertical-align:top;border-bottom:1px solid #dce3ee;padding:12px;overflow-wrap:anywhere}.compatibility th{color:#234f7b}.compatibility th[scope="row"]{width:34%}.compatibility td strong{display:block}.verification{font-size:13px;color:#53677b;margin:10px 0 22px}.agent{background:#172f46;color:#fff;border-radius:14px;padding:28px;display:grid;grid-template-columns:1fr auto;gap:14px 28px;align-items:center}.agent h2{font-size:20px;letter-spacing:-.035em;margin:0 0 8px}.agent p{margin:0;color:#c9d7e6;font-size:14px}.agent .button{background:#deebff;border-color:#deebff;color:#173c70;white-space:nowrap}.agent .prompt-details{grid-column:1/-1;margin:0;background:#10273b;border-color:#385069;color:#e5edf6}.agent summary{font-size:14px;padding:12px 16px}.agent .prompt{padding:14px 18px;margin:0;white-space:pre-wrap;font-size:14px;color:#dfebf9;overflow-wrap:anywhere}.agent a{color:#c3dbff}.agent details[open] summary{border-color:#385069}
section{padding:38px 0;scroll-margin-top:22px}.section-heading{display:flex;justify-content:space-between;align-items:baseline;gap:20px;margin-bottom:18px}.section-heading h2{margin:0;font-size:25px;letter-spacing:-.04em}.section-heading p{font-size:13px;color:#526679;margin:0}details{background:#fff;border:1px solid #d8e1ee;border-radius:12px;margin:12px 0;overflow:hidden}summary{cursor:pointer;padding:20px 23px;font-size:17px;font-weight:700}summary::marker{color:#2d63b4}summary .tag{font-size:12px;font-weight:500;color:#65798d;margin-left:9px}details[open]>summary{border-bottom:1px solid #e5eaf2}.detail-body{padding:4px 23px 23px}.detail-body p,.detail-body li{font-size:15px;color:#465d70}.detail-body li{margin:12px 0}.detail-body ol{padding-left:23px}.detail-body strong{color:#173b62}.detail-body code,.note code{font-family:ui-monospace,Consolas,monospace;font-size:.9em;overflow-wrap:anywhere}.notice{background:#f2f5fa;padding:16px 18px;border-radius:8px;font-size:14px!important}.doc-link{font-size:13px;margin-right:16px;display:inline-block;margin-top:5px}.code-head{display:flex;justify-content:space-between;align-items:center;gap:12px;background:#edf2f8;padding:10px 15px;border-radius:8px 8px 0 0;color:#4a5f73;font-size:13px}.copy{border:1px solid #b9c9df;border-radius:6px;background:#fff;color:#23466c;padding:6px 10px;font-size:13px;min-height:36px}.copy:hover{background:#e6effc}pre{margin:0 0 12px;padding:17px;background:#f5f7fb;border:1px solid #e0e7f1;border-top:0;border-radius:0 0 8px 8px;overflow:auto;max-width:100%;font-size:13px;line-height:1.7;word-break:normal}pre code{font-size:inherit!important;user-select:all}.instructions{white-space:pre-wrap}
.try{margin-top:20px;border-radius:10px;background:#eaf0fb;padding:20px}.try h3{font-size:16px;margin:0 0 6px}.try p{margin:0;font-size:15px;color:#284c75}.help{border-top:1px solid #d5deeb}.help h2{font-size:25px;margin:0 0 18px;letter-spacing:-.04em}.help summary{font-size:15px}.flow{font-size:15px!important;color:#244a79!important}footer{border-top:1px solid #dce3ee;padding:25px 0 32px;color:#526679;font-size:13px}.footer-row{display:flex;justify-content:space-between;gap:24px}footer a{color:#526679}.toast{position:fixed;left:50%;bottom:24px;transform:translateX(-50%);background:#172f45;color:#fff;border-radius:10px;padding:12px 22px;font-size:14px;box-shadow:0 8px 24px #10263d26;max-width:calc(100% - 32px);text-align:center;z-index:3}.toast:empty{display:none}[data-copy]{display:none}.js [data-copy]{display:inline-flex}
@media(max-width:760px){.wrap{padding:0 20px}nav{min-height:70px}.nav-links{gap:15px}.brand span{display:none}.intro{padding:34px 0 26px}h1{margin-bottom:16px}.apps{grid-template-columns:1fr;gap:12px}.app-card{padding:20px}.app-card.featured{padding-top:17px}.app-card h2{margin:5px 0 7px;font-size:21px}.app-card p{margin-bottom:13px}.agent{padding:22px;grid-template-columns:1fr;gap:16px}.agent .button{justify-self:start}.agent .prompt-details{grid-column:1}.section-heading{display:block}.section-heading p{margin-top:6px}section{padding:29px 0}summary{padding:17px}summary .tag{display:block;margin:2px 0 0 17px}.detail-body{padding:3px 17px 18px}.detail-body ol{padding-left:21px}.footer-row{display:block}.footer-row p{margin:0 0 10px}.code-head{padding:10px;font-size:12px}.copy{font-size:12px}pre{padding:13px;font-size:12px}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}
`;
const script = `
document.documentElement.classList.add('js');
const openTarget = () => {
  const target = document.getElementById(location.hash.slice(1));
  if (target && target.tagName === 'DETAILS') target.open = true;
};
openTarget(); window.addEventListener('hashchange', openTarget);
for (const link of document.querySelectorAll('a[href^="#"]')) link.addEventListener('click', () => {
  const target = document.getElementById(link.getAttribute('href').slice(1));
  if (target && target.tagName === 'DETAILS') target.open = true;
});
let toastTimer;
for (const button of document.querySelectorAll('[data-copy]')) {
  button.addEventListener('click', async () => {
    const source = document.getElementById(button.dataset.copy);
    if (!source) return;
    const status = document.getElementById('copy-status'); clearTimeout(toastTimer);
    try { await navigator.clipboard.writeText(source.textContent.trim()); status.textContent = '복사했습니다.'; }
    catch {
      for (let parent = source.parentElement; parent; parent = parent.parentElement) if (parent.tagName === 'DETAILS') parent.open = true;
      const range = document.createRange(); range.selectNodeContents(source);
      const selection = window.getSelection(); selection.removeAllRanges(); selection.addRange(range);
      source.scrollIntoView({block:'center'}); status.textContent = '내용을 선택했습니다. 직접 복사해 주세요.';
    }
    toastTimer = setTimeout(() => { status.textContent = ''; }, 5000);
  });
}
`;
const hash = (text: string) => createHash('sha256').update(text).digest('base64');
export const landingHeaders = {
  'Content-Security-Policy': `default-src 'none'; style-src 'sha256-${hash(style)}'; script-src 'sha256-${hash(script)}'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'`,
  'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'no-referrer', 'Cache-Control': 'no-cache',
};
export const landingHtml = `<!doctype html>
<html lang="ko"><head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
  <title>TaxLab 법령 · 내 AI에 연결하기</title>
  <meta name="description" content="Claude 웹·PC, ChatGPT 웹·데스크톱, Gemini·Antigravity의 연결 방법과 지원 조건을 확인하세요.">
  <link rel="canonical" href="https://law.taxlab.kr/"><style>${style}</style>
</head><body>
  <a class="skip" href="#main">본문으로 이동</a>
  <header><nav class="wrap" aria-label="주 메뉴"><a class="brand" href="/">TaxLab<span>법령 MCP</span></a><div class="nav-links"><a href="#connect">연결 안내</a><a href="#help">도움말</a></div></nav></header>
  <main id="main" class="wrap">
    <div class="intro"><p class="eyebrow">TAXLAB LEGAL</p><h1>내 AI에<br>법령 검색을 더하세요.</h1><p class="lede">법령을 찾고, 원문을 읽고, 작성한 초안을 점검하세요.<br>쓰는 앱을 고르면 연결 방법을 안내해 드립니다.</p><p class="key-note"><strong>운영자에게 받은 TaxLab 접속키</strong>가 필요합니다. 앱별 추가 조건은 아래에서 확인하세요.</p></div>
    <div class="apps" aria-label="사용하는 AI 고르기">
      <article class="app-card featured"><span class="badge">PC 앱 설치 · 웹은 조건 확인</span><h2>Claude</h2><p>PC 앱은 설치파일로 연결합니다.<br>웹은 조직의 인증 메뉴에 따라 달라집니다.</p><a class="button primary" href="/downloads/taxlab-law.mcpb" download>Claude 설치파일 받기</a><a class="sub-link" href="#claude">PC 설치 방법 →</a><a class="sub-link" href="#claude-web">Claude 웹 지원 조건 →</a></article>
      <article class="app-card"><span class="badge">웹과 데스크톱의 설정이 다릅니다</span><h2>ChatGPT</h2><p>웹은 내 GPT의 Actions로 연결합니다.<br>PC 앱은 MCP 설정과 로컬 연결 프로그램을 씁니다.</p><a class="button" href="#chatgpt">ChatGPT 설정하기 →</a><a class="sub-link" href="#chatgpt-desktop">데스크톱 연결 방법 →</a></article>
      <article class="app-card"><span class="badge">CLI 지원 · 국내 일반 웹·앱 불가</span><h2>Gemini</h2><p>Gemini CLI에서 연결할 수 있습니다.<br>한국에서 쓰는 일반 웹·모바일은 현재 지원되지 않습니다.</p><a class="button" href="#gemini">Gemini 연결 안내 →</a></article>
      <article class="app-card"><span class="badge">앱 · IDE · CLI</span><h2>Antigravity</h2><p>MCP 설정 파일에 서버와 접속키를 넣습니다.<br>Gemini CLI와 다른 설정을 사용합니다.</p><a class="button" href="#antigravity">Antigravity 연결 안내 →</a></article>
    </div>
    <div class="agent"><div><h2>설정은 AI에게 맡기고 싶다면</h2><p>아래 요청문을 PC 설정이 가능한 AI 에이전트에 붙여넣으세요.<br>일반 채팅에서는 수동 설정 안내를 받을 수 있습니다.</p></div><button class="button" data-copy="agent-prompt">AI 설정 요청문 복사</button><details class="prompt-details"><summary>요청문 보기</summary><p class="prompt" id="agent-prompt">${escapeHtml(agentPrompt)}</p><p class="prompt"><a href="/setup.md">AI용 연결 안내 문서 열기</a></p></details></div>
    <section id="connect" aria-labelledby="connect-title"><div class="section-heading"><h2 id="connect-title">앱별 연결 안내</h2><p>공식 안내 확인일 · 2026.09.21</p></div>
      <table class="compatibility"><caption>현재 TaxLab 연결 지원 범위</caption><thead><tr><th scope="col">사용하는 앱</th><th scope="col">가능 여부와 조건</th></tr></thead><tbody>
        <tr><th scope="row"><a href="#claude">Claude PC 앱</a></th><td><strong>설치파일 제공</strong>로컬 확장 사용. 실제 Claude 앱 설치 과정은 미검증.</td></tr>
        <tr><th scope="row"><a href="#claude-web">Claude 웹</a></th><td><strong>일부 조직만 조건부 지원</strong>Request headers 베타 메뉴가 없으면 현재 직접 연결 불가.</td></tr>
        <tr><th scope="row"><a href="#chatgpt">ChatGPT 웹</a></th><td><strong>GPT Actions 설정 제공</strong>GPT 만들기가 가능한 계정 필요. 실제 GPT 편집기 실행은 미검증.</td></tr>
        <tr><th scope="row"><a href="#chatgpt-desktop">ChatGPT 데스크톱</a></th><td><strong>MCP 설정이 있는 앱에서 로컬 연결</strong>연결 프로그램과 실행환경 필요. 실제 앱 UI 과정은 미검증.</td></tr>
        <tr><th scope="row"><a href="#gemini">Gemini CLI</a></th><td><strong>SSE·접속키 설정 지원</strong>CLI 0.60.0에서 운영 서버 초기 연결·ping 확인.</td></tr>
        <tr><th scope="row"><a href="#gemini-web">Gemini 웹·모바일</a></th><td><strong>국내 일반 계정은 현재 연결 불가</strong>미국 등 공식 조건 해당 계정도 TaxLab 인증 호환은 미검증.</td></tr>
        <tr><th scope="row"><a href="#antigravity">Antigravity</a></th><td><strong>원격 MCP·접속키 설정 지원</strong>전용 설정 제공. 실제 앱 UI에서 도구 실행은 미검증.</td></tr>
      </tbody></table>
      <p class="verification">공식 문서의 지원 조건과 TaxLab 연결 방식을 대조했습니다. 설정 저장만으로 연결 완료가 되지는 않습니다. 각 앱에서 실제 도구 목록이 나오는지 확인하세요.</p>
      <details id="claude" open><summary>Claude <span class="tag">PC 앱에서 설치파일로 연결</span></summary><div class="detail-body"><ol><li><a href="/downloads/taxlab-law.mcpb" download><strong>Claude 설치파일(.mcpb)</strong></a>을 내려받으세요.</li><li>Claude PC 앱의 <strong>설정 → 확장(Extensions) → 고급 설정 → Install Extension</strong>에서 파일을 선택하세요.</li><li><strong>TaxLab 접속키</strong> 입력창에 운영자에게 받은 키를 넣고 활성화하세요.</li><li>새 대화에서 TaxLab 도구를 켜고 아래 예시처럼 요청하세요.</li></ol><p class="notice">이 설치파일은 Claude PC 앱용입니다. 웹 연결은 아래 별도 조건을 확인하세요. 조직 계정은 관리자의 확장 설치 허용이 필요할 수 있습니다.</p><a class="doc-link" href="https://support.claude.com/en/articles/10949351-getting-started-with-local-mcp-servers-on-claude-desktop">Claude 공식 설치 안내 ↗</a></div></details>
      <details id="claude-web"><summary>Claude 웹 <span class="tag">일부 조직의 헤더 인증 베타만 가능</span></summary><div class="detail-body"><p><strong>Request headers 메뉴가 없는 계정은 현재 TaxLab에 직접 연결할 수 없습니다.</strong> Claude의 원격 MCP 기능 자체는 지원되지만, TaxLab은 접속키를 요청 헤더로 받아야 합니다.</p><ol><li>조직 관리자가 <strong>Organization settings → Connectors → Add → Custom → Web</strong>을 엽니다.</li><li>MCP 서버 주소에 <code>${mcpEndpoint}</code>를 넣습니다.</li><li>인증은 <strong>No sign-in</strong>, <strong>Request headers</strong>에 이름 <code>x-api-key</code>와 접속키를 입력합니다. 연결 방식은 SSE입니다.</li><li>저장한 뒤 <strong>Customize → Connectors</strong>에서 연결하고 새 대화에서 TaxLab 도구를 확인합니다.</li></ol><p class="notice">헤더 인증은 일부 조직 대상 베타입니다. No sign-in을 골라도 접속키 헤더는 필요합니다. OAuth Client Secret 칸이나 웹 주소에 접속키를 넣지 마세요. 실제 Claude 웹 계정에서의 연결은 아직 미검증입니다.</p><a class="doc-link" href="https://claude.com/docs/connectors/custom/remote-mcp">Claude 웹 설정·베타 조건 ↗</a></div></details>
      <details id="chatgpt"><summary>ChatGPT 웹 <span class="tag">내 GPT에 설정 가져오기</span></summary><div class="detail-body"><ol><li>ChatGPT 웹에서 <strong>GPTs → 만들기 → 구성 → 새 작업(Action)</strong>을 여세요. GPT 만들기 기능이 있는 계정이 필요합니다.</li><li><strong>URL에서 가져오기</strong>에 아래 설정 주소를 넣으세요.</li></ol>${codeBlock('openapi-url', '설정 주소', 'https://law.taxlab.kr/openapi.json')}<ol start="3"><li><strong>인증 → API Key → Bearer</strong>를 선택하고 접속키만 입력하세요. 키 앞에 <code>Bearer</code>를 다시 붙이지 마세요.</li><li>아래 지침을 GPT의 <strong>지침(Instructions)</strong>에 붙여넣으세요.</li></ol><button class="button" data-copy="gpt-instructions">GPT 지침 복사</button><details><summary>GPT 지침 보기</summary><div class="detail-body"><p class="instructions" id="gpt-instructions">${escapeHtml(gptInstructions)}</p></div></details><ol start="5"><li><strong>listTaxlabTools</strong>를 테스트해 도구 목록이 나오면 <strong>나만 사용</strong>으로 저장하세요.</li></ol><p class="notice">이 방식은 <strong>GPT Actions</strong>로 같은 법령 서버에 연결합니다. 공유 접속키를 넣은 GPT는 공개 배포하지 마세요. 현재 TaxLab 주소를 원격 MCP 플러그인에 바로 등록하는 방식은 지원하지 않습니다. 웹에서 만든 GPT의 Actions가 모든 데스크톱 앱에서 동작하는지도 확인되지 않았습니다. PC 앱은 아래 안내를 확인하세요.</p><a class="doc-link" href="/downloads/chatgpt-actions.json" download>설정 파일 받기</a><a class="doc-link" href="https://developers.openai.com/api/docs/actions/getting-started">ChatGPT 공식 설정 안내 ↗</a><a class="doc-link" href="https://developers.openai.com/api/docs/actions/authentication">인증 안내 ↗</a></div></details>
      <details id="chatgpt-desktop"><summary>ChatGPT 데스크톱 <span class="tag">MCP 설정이 있는 앱 · 로컬 연결</span></summary><div class="detail-body"><p><strong>설정에 MCP servers 메뉴가 있는 앱에서 사용할 수 있는 경로입니다.</strong> 현재 TaxLab은 이 메뉴의 URL 방식과 바로 호환되지 않아 로컬 연결 프로그램을 거칩니다.</p><ol><li>PC 설정이 가능한 AI에 위의 <strong>AI 설정 요청문</strong>을 보내고 “ChatGPT 데스크톱의 STDIO 연결로 설정해줘”라고 덧붙이세요.</li><li>직접 설정한다면 <a href="/downloads/taxlab-bridge.zip" download>로컬 연결 파일(ZIP)</a>을 풀고 <a href="/setup.md">상세 설정 안내</a>에 따라 실행환경과 접속키를 준비하세요.</li><li><strong>Settings → MCP servers → Add server → STDIO</strong>에서 연결 프로그램의 명령·경로·접속키 환경 설정을 등록합니다.</li><li>저장 후 <strong>Restart</strong>를 누르고 <code>/mcp</code>에서 TaxLab 도구가 연결됐는지 확인합니다.</li></ol><p class="notice">MCP servers 메뉴가 없는 앱에서는 이 방법을 사용할 수 없습니다. <a href="#chatgpt">웹의 GPT Actions</a>를 이용하세요. 로컬 연결 프로그램의 통신 검사는 통과했지만 ChatGPT 데스크톱 UI의 전체 설치·실행은 아직 미검증입니다. 웹에 자동 연결되지는 않습니다.</p><a class="doc-link" href="/downloads/chatgpt-desktop.toml" download>고급 설정 템플릿 받기</a><a class="doc-link" href="https://learn.chatgpt.com/docs/extend/mcp">OpenAI 데스크톱 MCP 공식 안내 ↗</a></div></details>
      <details id="gemini"><summary>Gemini CLI <span class="tag">PC 터미널에서 연결</span></summary><div class="detail-body"><p>Gemini CLI에서는 <strong>AI 설정 요청문</strong>으로 설정을 맡기거나, 기존 <code>~/.gemini/settings.json</code>의 <code>mcpServers</code>에 아래 항목을 추가하세요. 프로젝트만 연결하려면 그 프로젝트의 <code>.gemini/settings.json</code>을 사용합니다.</p><p><code>type: "sse"</code>를 유지하세요. 접속키는 CLI 실행 환경의 <code>TAXLAB_API_KEY</code>에 넣고 CLI를 다시 여세요. <strong>기존 파일 전체를 덮어쓰지 마세요.</strong></p>${codeBlock('gemini-config', 'Gemini CLI 설정', geminiConfig)}<p>터미널의 <code>gemini mcp list</code> 또는 대화의 <code>/mcp list</code>로 상태를 보고, <code>/mcp desc</code>에서 <code>search_law</code> 등 도구를 확인하세요.</p><a class="doc-link" href="/downloads/gemini-settings.json" download>Gemini CLI 설정 파일 받기</a><a class="doc-link" href="https://geminicli.com/docs/tools/mcp-server/">Gemini CLI 공식 안내 ↗</a></div></details>
      <details id="gemini-web"><summary>Gemini 웹·모바일 <span class="tag">국내 일반 계정은 현재 연결 불가</span></summary><div class="detail-body"><p><strong>한국에서 사용하는 일반 Gemini 웹·모바일에는 현재 TaxLab을 연결할 수 없습니다.</strong> CLI 설정을 일반 앱에 적용하는 방식도 아닙니다.</p><p>Google의 사용자 지정 MCP 앱은 미국·18세 이상·개인 계정·영어·Keep Activity 켜기 조건이 있습니다. 조건에 해당하는 계정은 웹의 Settings → Connected Apps → Custom apps에서 추가하지만, TaxLab 접속키 인증과의 호환은 아직 확인되지 않았습니다.</p><a class="doc-link" href="https://support.google.com/gemini/answer/17209137?co=GENIE.Platform%3DDesktop&amp;hl=en-GA">Google의 연결 조건 확인 ↗</a></div></details>
      <details id="antigravity"><summary>Antigravity <span class="tag">앱 · IDE · CLI 원격 연결</span></summary><div class="detail-body"><ol><li><strong>Antigravity 2.0</strong>: Settings → Customizations → Installed MCP Servers → Open MCP Config.<br><strong>IDE</strong>: Agent 패널의 … → MCP Servers → Manage MCP Servers → View raw config.<br><strong>CLI</strong>: <code>agy mcp add</code>로 등록합니다. <a href="/setup.md">OS별 등록 명령</a>을 확인하세요.</li><li>기존 <code>mcpServers</code>에 아래 항목을 병합하고 <code>YOUR_API_KEY</code>만 로컬에서 접속키로 바꾸세요.</li></ol>${codeBlock('antigravity-config', 'Antigravity 설정', antigravityConfig)}<ol start="3"><li>저장 후 MCP 화면의 <strong>Refresh</strong>를 누르세요. CLI는 <code>/mcp</code> 관리 화면에서 Reload합니다.</li><li>TaxLab 서버가 연결되고 <code>search_law</code> 등 도구가 나오는지 확인하세요. <code>agy mcp list</code>의 enabled 표시만으로 인증 성공이 확인되지는 않습니다.</li></ol><p class="notice">Antigravity는 <code>serverUrl</code>, Gemini CLI는 <code>url</code>을 사용합니다. 앱에서 직접 연 설정 파일에 병합하세요. 설정 파일에는 접속키가 들어가므로 공개하거나 Git에 올리지 마세요. 공식 설정은 확인했으며 실제 Antigravity 앱 UI에서의 도구 실행은 미검증입니다.</p><a class="doc-link" href="/downloads/antigravity-mcp.json" download>Antigravity 설정 파일 받기</a><a class="doc-link" href="https://antigravity.google/docs/mcp">Antigravity 공식 안내 ↗</a></div></details>
      <details id="advanced"><summary>다른 AI 에이전트에서 연결 <span class="tag">Claude Code · Cursor · VS Code 등</span></summary><div class="detail-body"><p>먼저 <strong>AI 설정 요청문</strong>을 사용하세요. 직접 설정하려면 아래 주소와 인증 헤더를 사용합니다.</p>${codeBlock('endpoint', 'MCP 주소', mcpEndpoint)}<p>방식: SSE · 인증: <code>Authorization: Bearer YOUR_API_KEY</code> 또는 <code>x-api-key: YOUR_API_KEY</code></p><p>현재 OAuth 로그인과 Streamable HTTP는 제공하지 않습니다. <strong>모든 앱에 주소만 넣어 연결되는 것은 아닙니다.</strong> ChatGPT 데스크톱·Codex는 <a href="#chatgpt-desktop">로컬 연결 안내</a>, Claude Code는 <a href="/setup.md">AI용 안내 문서</a>를 확인하세요.</p><details><summary>Cursor 설정 예시</summary><div class="detail-body">${codeBlock('cursor-config', 'Cursor 설정', cursorConfig)}<p><code>YOUR_API_KEY</code>는 로컬에서 실제 키로 교체하고 설정 파일을 공개하지 마세요.</p></div></details><details><summary>VS Code 로컬 Copilot 설정 예시</summary><div class="detail-body">${codeBlock('vscode-config', 'VS Code 설정', vscodeConfig)}<p>기존 <code>servers</code>와 <code>inputs</code>에 병합하세요. 시작 시 접속키 입력창이 나타납니다.</p></div></details></div></details>
      <div class="try"><h3>연결 후 이렇게 요청해 보세요</h3><p>“TaxLab으로 근로기준법을 찾아 원문 링크와 시행일을 알려줘. 확인하지 못한 내용은 따로 표시해줘.”</p></div>
    </section>
    <section class="help" id="help" aria-labelledby="help-title"><h2 id="help-title">궁금한 점</h2>
      <details id="research"><summary>근거와 논리를 함께 점검하려면?</summary><div class="detail-body"><p>연결한 AI에게 아래처럼 요청하세요. 실제로 읽은 원문과 주장별 인용을 대조하고, 빠진 사실·반대 근거·시점의 공백을 보여줍니다.</p><p class="prompt" id="research-prompt">TaxLab 연구 하네스로 쟁점을 나누고 실제 원문과 반대 근거를 읽은 뒤, 주장별 인용과 빠진 사실을 검사해줘. 다른 쟁점의 근거를 사용했다면 연결 이유와 한계도 밝혀줘.</p><button class="button" data-copy="research-prompt">연구 요청문 복사</button><p>구조 검사를 통과해도 법률 결론의 정답을 인증하지 않습니다. 확인되지 않은 부분은 조건부 또는 유보로 남깁니다. 연구 기록은 30분 또는 서버 재시작 시 사라지며, 공개할 정정안은 아래 PR 절차에서 별도로 확인합니다.</p></div></details>
      <details><summary>접속키는 어디서 받나요?</summary><div class="detail-body"><p>TaxLab 사용을 안내한 운영자에게 받으세요. 설치파일에는 키가 들어 있지 않습니다. 키를 채팅이나 웹 주소에 붙이지 말고, 안내된 앱 설정에 입력하세요.</p></div></details>
      <details><summary>연결했는데 응답이 없어요.</summary><div class="detail-body"><p>접속키가 정확한지, TaxLab 도구가 켜져 있는지 확인한 뒤 새 대화에서 다시 시도하세요. <a href="/health">서버 상태</a>가 <code>ok</code>여도 앱 인증까지 성공한 것은 아닙니다. 잠시 후 재시도해도 연결이 안 되면 키를 제외한 오류 메시지와 사용 앱을 운영자에게 알려주세요.</p></div></details>
      <details id="improvements"><summary>더 확실한 근거가 나오면 PR로 남길 수 있나요?</summary><div class="detail-body"><p><strong>AI가 기존 답변의 오류를 인정하면 정정 요지·근거·다음 점검 항목을 준비하고 “이 정정 내용을 PR로 제안할까요?”라고 묻습니다.</strong> 게시할 내용을 확인하고 동의하면 실제 교정 자료 PR 링크를 받습니다.</p><p class="flow">반박·새 근거 확인 → 정정안 미리보기 → 사용자 동의 → draft PR → 검수·머지</p><p>개인정보를 뺀 공개 가능한 내용만 제안합니다. 작성 AI의 검토와 별도 AI 검수는 구분하며, PR에서 별도 검수 상태를 확인하세요. 자동 머지는 하지 않습니다. GitHub에서 머지된 교정 자료는 이후 조회의 참고 항목으로 제공됩니다.</p><p>AI가 제안을 놓쳤다면 “방금 정정한 내용으로 PR 제안을 준비해줘”라고 요청하세요. MCP는 호출하지 않은 대화를 직접 감시하지 않습니다. 실행 코드 자동 패치·재수정 작업은 별도 기능입니다.</p></div></details>
      <details id="data"><summary>어떤 정보가 전송되나요?</summary><div class="detail-body"><p>AI 앱에서 도구 실행을 허용하면 질의·도구 인자·검사를 요청한 초안이 TaxLab 서버로 전송됩니다. 조회에 필요한 검색어·식별자는 원문 제공처로 전달될 수 있고, 결과는 사용하는 AI 앱으로 돌아갑니다. 앱 자체의 대화 저장 정책도 적용됩니다.</p><p>교정 PR은 미리보기에 표시된 내용과 출처를 사용자의 동의 후 지정 GitHub 저장소에 게시합니다. 준비된 제안과 게시 결과는 서버에 보관합니다. 공유 접속키는 개인별 비공개 보관함이 아니므로 공개 가능한 정정 자료만 제출하세요.</p><p>Claude 설치파일의 접속키는 앱의 비밀값 설정에서 관리합니다. 주민등록번호 등 법령 검색에 필요 없는 개인정보는 질의에 넣지 마세요.</p></div></details>
      <details><summary>검색 결과가 나오면 법률 검증까지 끝난 건가요?</summary><div class="detail-body"><p>조회 성공만으로 최신성이나 사건 적용이 확정되지는 않습니다. 사건 기준일·연혁·부칙·후속 해석을 확인해야 합니다. 초안 점검도 정해진 범위만 다루며, 확인되지 않은 내용은 미검증으로 표시합니다.</p></div></details>
    </section>
  </main>
  <footer><div class="wrap footer-row"><p>TaxLab · 법령 조회와 초안 점검</p><p><a href="/setup.md">AI용 연결 안내</a> · <a href="#data">데이터 전송 안내</a> · <a href="#improvements">오류 신고·PR</a></p></div></footer>
  <div class="toast" id="copy-status" role="status" aria-live="polite"></div><script>${script}</script>
</body></html>`;
